### ISSUE TITLE
Checksum mismatch for openjdk1.8-latest 1.8.0_131

### ISSUE THREAD

**Issue by aleliaert** [cloudfoundry/ruby-buildpack#80]
Seeing "Buildpack::Packager::CheckSumError: File: openjdk1.8-latest, version: 1.8.0_131 downloaded at location https://java-buildpack.cloudfoundry.org/openjdk/trusty/x86_64/openjdk-1.8.0_131.tar.gz
	is reporting a different checksum than the one specified in the manifest"

This is what I did:
```
unix> git clone https://github.com/cloudfoundry/ruby-buildpack.git
unix> cd ruby-buildpack/
unix> git submodule update --init
unix> BUNDLE_GEMFILE=cf.Gemfile bundle
unix> BUNDLE_GEMFILE=cf.Gemfile bundle exec buildpack-packager --cached
```

More clues:
```
unix> wget https://java-buildpack.cloudfoundry.org/openjdk/trusty/x86_64/openjdk-1.8.0_131.tar.gz
unix> md5sum openjdk-1.8.0_131.tar.gz
6fb780aa58cfd592fe2542aeec373215  openjdk-1.8.0_131.tar.gz
```

From manifest.yml:
```
- name: openjdk1.8-latest
  version: 1.8.0_131
  uri: https://java-buildpack.cloudfoundry.org/openjdk/trusty/x86_64/openjdk-1.8.0_131.tar.gz
  md5: 41cbf08b9a72db7a1a53a74c75a819ba
  cf_stacks:
  - cflinuxfs2
```
Thanks!  Having a lot of fun learning Cloud Foundry!
